pipeline {
  agent {
    dockerfile {
      filename 'dockerfile'
    }
  }
  environment {
      CI = 'true'
  }
  stages {
    stage('Build') {
      steps {
        sh 'npm install'
      }
    }
    stage('Test') {
      steps {
          sh './test.sh'
      }
    }
  }
}